version: '3.8'

services:
  node_backend:
    container_name: docker_pg_sq
    image: docker_pg_sq
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

    volumes:
      - nps_data:/var/lib/postgresql/nps_data

volumes:
  nps_data: {}
