version: '3.8'

services:
  node_backend:
    container_name: docker_pg_sq
    image: docker_pg_sq
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=node_db
      - JWT_SECRET=abc123
    depends_on:
      node_db:
        condition: service_healthy

  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - nps_data:/var/lib/postgresql/nps_data

volumes:
  nps_data: {}
